### ISSUE TITLE
Differences among gait3d models

### ISSUE THREAD

**Issue by modenaxe** [mad-lab-fau/BioMAC-Sim-Toolbox#4]
Hello,
thank you for sharing this code and models, they certainly can be very useful!
I hope I am not asking a beginner question but I was wondering if someone could help me understanding the differences between the gait3d models made available [here](https://github.com/mad-lab-fau/BioMAC-Sim-Toolbox/tree/main/src/model/gait3d/c_files/gait3d_pelvis213):
* "pelvis213" / "pelvis213_raw": is "213" the order of rotations between pelvis and ground?
* "pelvis213_FK" / "pelvis213_FK_raw"
* "pelvis213_NoDer" / * "pelvis213_NoDer_raw"
* "pelvis213_multibody"

Thank you in advance!

Luca

**Comment by adkoele** [comment]
Hi Luca,

That is correct. 213 is the order of rotations between the pelvis and the ground. We used for change of direction movements, since the first angle is then the body rotation around the vertical axis (see: https://www.nature.com/articles/s41598-020-73856-w).

I guess your second question is: why do we have the different codes? The reason is computational speed. Originally, all was calculated in the same c code, but we do not, for example, always need derivatives, so we realized that we could save a lot of time there, since the functions are called many times in an optimization. You can see how _FK and _NoDer are called in gait3d_pelvis213.c.
- pelvis213_FK: calculates the forward kinematics (FK), i.e., the XYZ location of all the joints in space from the joint angles and body parameters.
- pelvis213_NoDer: calculates the dynamics without calculating the derivatives (NoDer = no derivatives)
- pelvis213_multibody: the header file with the multibody dynamics parameters. It is called by gait3d_pelvis213.h, where the muscle parameters are initialized. Basically, the _multibody header file contains all that is required for the code generated by Autolev, and gait3d_pelvis213.h contains everything related to the muscle dynamics, which is coded directly in c. They could have also been combined.

I hope this helps! Let me know if you have further questions.
Anne

**Comment by modenaxe** [comment]
Thank you Anne, this seems clear - I will look around a bit more and let you know if I have any additional question...
